[CRITICAL:2024-09-05 17:05:12,798] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\database_connection.py:31} - Database Connection Error : connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres1"

[CRITICAL:2024-09-05 17:05:12,798] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\task.py:15} - Failed to connect to the database.
[CRITICAL:2024-09-05 17:05:12,798] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\task.py:63} - An error occurred: 'NoneType' object has no attribute 'cursor'
[CRITICAL:2024-09-05 17:08:36,895] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\database_connection.py:31} - Database Connection Error : connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres1"

[CRITICAL:2024-09-05 17:08:36,895] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\task.py:15} - Failed to connect to the database.
[CRITICAL:2024-09-05 17:08:36,895] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\task.py:63} - An error occurred: 'NoneType' object has no attribute 'cursor'
[CRITICAL:2024-09-05 17:08:50,462] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\database_connection.py:31} - Database Connection Error : connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres1"

[CRITICAL:2024-09-05 17:08:50,462] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\task.py:15} - Failed to connect to the database.
[CRITICAL:2024-09-05 17:08:50,462] - {C:\Users\kevin.mensah\Desktop\python\projects\command_link_task_manager\task.py:63} - An error occurred: 'NoneType' object has no attribute 'cursor'
